name: Build
on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Zip production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: zip

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Artifact build files
        uses: actions/upload-artifact@v3
        with:
          name: filez-${{ steps.package-version.outputs.current-version}}.mds.zip
          path: filez-${{ steps.package-version.outputs.current-version}}.mds.zip

#      - name: Veracode Upload And Scan
#        uses: veracode/veracode-uploadandscan-action@0.2.4
#        with:
#          appname: 'Minima APK + MiniDAPPS'
#          createprofile: false
#          filepath: 'filez-0.0.2.mds.zip'
#          vid: '${{ secrets.API_ID }}'
#          vkey: '${{ secrets.API_KEY }}'
